# VulnerabilityPatcher by CoolJWB.

# Patches: DeathPotions, DeathItems, CrashItems, Books, RougeEntity, Arrows, Riptide, FollowRange, DisconnectItems,
# EntityTag, Blocks, StructureBlocks, Chunks, ItemFrames, HandSwitch, Fireworks, Chests, Beehives, Skulls, ItemNames.
# All patches added in the list below will be activated on server startup.
Patches:
  - DeathPotions # Potions that kill creative players
  - DeathItems # Item that makes a player unable to respawn
  - CrashItems # Items that crash the player client
  - Books # Books that have malicious commands
  - RougeEntity # Entities that move quicker then allowed
  - Arrows # Arrows that crash the server
  - Riptide # Enchantment that crashes the server and or clients
  - FollowRange # Attribute that crashes the server
  - DisconnectItems # Items that disconnect players from the server
  - EntityTag # Customized mob eggs
  - Spawner # Mob spawners with large spawn amounts
  - StructureBlocks # Used to modify the world
  - Chunks # Spawn command that crashes the server
  - ItemFrames # Item frames that crashes the server
  - HandSwitch # Hand switcher hack that crashes clients and possibly the server
  - Fireworks # Lags the clients when too many effects
  #- Containers # Disables container drops (chests and such) fully to avoid large item drops (only recommended for creative servers).
  - Beehives # Removes all NBT data from any EntityBlockStorage such as beehives
  - Skulls # Purges empty skull owner IDs
  - ItemNames # Removes item names with events in them.
  - OversizedSigns # Removes signs with NBT tag

# All entities added below will be blocked to use in a spawn egg.
BlockedEntityTags:
  - lightning_bolt
  - item_frame
  - falling_block
  - area_effect_cloud
  - phantom

Commands:
  Help:
    Permission: vulnerability.help
  Version:
    Permission: vulnerability.version
  Reload:
    Permission: vulnerability.reload
  Delete:
    Permission: vulnerability.delete
  BlockTags:
    Permission: vulnerability.tags.block
  UnblockTags:
    Permission: vulnerability.tags.unblock
  EnablePatch:
    Permission: vulnerability.patch.enable
  DisablePatch:
    Permission: vulnerability.patch.disable

# Notifications of players using blocked items will be sent to all players that have the permission below (if it's enabled).
Notify:
  Enabled: false
  Permission: vulnerability.notify

# Security Mode (EASY : MEDIUM : STRICT).
# EASY: Blocks dangerous items loosely (should still be secure).
# MEDIUM: Blocks dangerous items strictly (more secure by checking all items in containers).
# STRICT: Blocks all items that have any potential issue (more secure but removes enchants over level 5 and removes all attributes).
SecurityMode: "EASY"

# DevMode should be set to false, unless you're a developer of this plugin.
DevMode: false

# Do not modify this value, used to define the configurations version for future versions.
ConfVersion: 0