name: VulnerabilityPatcher
version: 2.0.1
api-version: 1.17
main: me.cooljwb.vulnerabilitypatcher.VulnerabilityPatcher
authors: [CoolJWB]
description: Patches vulnerabilities that cause server instabilaty.
commands:
  vulnerabilitypatcher:
    aliases: [vp]
    description: The main command for VulnerabilityPatcher.
  getnbt:
    description: Reveals an items NBT data.
  getlag:
    description: Scans common sources for lag and reports back the most probable causes.